[build-system]
requires = ["uv_build >= 0.11.29, < 0.12"]
build-backend = "uv_build"


[project]
name = "moredantic"
description = "A python library created on top of Pydantic that adds some functionalities to the Base and Root Models. Also adds some new data shapes models, new annotations and new decorators."
version = "0.0.2"
readme = "README.md"
license = "MIT"
license-files = ["LICEN[CS]E*"]
authors = [
    { name = "Ricardo JRSM Vieira", email = "ricardojrsmvieira@gmail.com" }
]
maintainers = [
    { name = "Ricardo JRSM Vieira", email = "ricardojrsmvieira@gmail.com" }
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Typing :: Typed"
]
requires-python = ">= 3.13"
dependencies = [
    "debug-group ~= 0.0.5",
    "pydantic == 2.13.4",
]


[dependency-groups]
dev = [
    "ruff >= 0.15.22, < 0.16",
    "pyright[nodejs] >= 1.1.411, < 1.2",
    "pip-audit >= 2.10.1, < 2.11"
]


[project.urls]
Homepage = "https://github.com/ricardojrsmvieira/moredantic"
Issues = "https://github.com/ricardojrsmvieira/moredantic/issues"
