####################################################################################################
#                                                                                                  #
#                                             GENERAL                                              #
#                                                                                                  #
####################################################################################################
line-length = 100


####################################################################################################
#                                                                                                  #
#                                               LINT                                               #
#                                                                                                  #
####################################################################################################
[lint]
select = ['ALL']
ignore = [
  ##################################################################################################
  # => RULES IGNORED BECAUSE THEY ARE SPECIFIC TO A PARTICULAR LIBRARY OR FRAMEWORK:
  # https://pypi.org/project/apache-airflow/
  'AIR',
  # https://pypi.org/project/fastapi/
  'FAST',
  # https://pypi.org/project/Flask/
  'S201',
  # https://pypi.org/project/Django/
  'S308',
  'S610',
  'S611',
  'DJ',
  # https://pypi.org/project/paramiko/
  'S507',
  'S508',
  'S601',
  # https://pypi.org/project/pysnmp/
  'S509',
  # https://pypi.org/project/Jinja2/
  'S701',
  # https://pypi.org/project/Mako/
  'S702',
  # https://pypi.org/project/MarkupSafe/
  'S704',
  # https://pypi.org/project/pytest/
  # 'PT',
  # 'RUF043',
  # 'RUF061',
  # https://pypi.org/project/numpy/
  'NPY',
  # https://pypi.org/project/pandas/
  'PD',
  # The Ruff Formatter
  'RUF028',

  ##################################################################################################
  # => OTHER RULES IGNORED BY PERSONAL PREFERENCE:
  'COM812',
  'FIX',
  'PYI051',
  'Q003',
  'SIM105',
  'TID253',
  'TD002',
  'TC',
  'D204'
]

####################################################################################################
#                                            LINT.ISORT                                            #
####################################################################################################
[lint.isort]
combine-as-imports = true
force-wrap-aliases = true
lines-after-imports = 2

[lint.isort.import-heading]
future = "---> Future imports <--- #"
standard-library = "---> Standard library imports <--- #"
third-party = "---> Third party imports <--- #"
first-party = "---> First party imports <--- #"
local-folder = "---> Local imports <--- #"

####################################################################################################
#                                        LINT.FLAKE8-BANDIT                                        #
####################################################################################################
[lint.flake8-bandit]
check-typed-exception = true

####################################################################################################
#                                       LINT.FLAKE8-BUILTINS                                       #
####################################################################################################
[lint.flake8-builtins]
strict-checking = true
allowed-modules = ['types']

####################################################################################################
#                                        LINT.FLAKE8-QUOTES                                        #
####################################################################################################
[lint.flake8-quotes]
inline-quotes = "single"
multiline-quotes = "single"
docstring-quotes = "double"

####################################################################################################
#                                           LINT.MCCABE                                            #
####################################################################################################
[lint.mccabe]
max-complexity = 10

####################################################################################################
#                                         LINT.PYDOCSTYLE                                          #
####################################################################################################
[lint.pydocstyle]
convention = "numpy"

####################################################################################################
#                                           LINT.PYLINT.                                           #
####################################################################################################
[lint.pylint]
max-returns = 6
max-branches = 12
max-args = 5
max-statements = 50
